### ISSUE TITLE
Questions about the function of scCODE

### ISSUE THREAD

**Issue by yunbokai** [XZouProjects/scCODE#3]
Dear Professor:

I tried my seurat data "st.RNA" with function:

`scCODE_data <- st.RNA@assays$Spatial@counts`
`scCODE_group <- st.RNA@meta.data$seurat_clusters`
`scCODE_results<-scCODE(data,group,light = TRUE,top_ranked=5)`

My scCODE_group type is a factor with 9 levels. I thought the function of scCODE is similar to "FindAllMarkers" in Seurat before, but the result seems that it only works for 2 levels just like the example of scCODE. It makes me confused. Can you help me?

Thanks,
18K

**Comment by XZouProjects** [comment]
Hi,

The scCODE package now does only work for the comparasion of 2 groups of cells. To acheive the function like "FindAllMarkers" in Seurat, a solution now could be making the group type 1 as the group factor 1, and the others (group 2,3,...) as group 2. By this way we can get the DE genes of one type of cells each time, but it would be complicated to get the DE genes of each cell group. 

We would considering the funtion of mutiple group comparing in the next version of package. Thank you!

**Comment by yunbokai** [comment]
Hi
Thanks a lot for your answer. I‘m looking foward to the new version!
Best wishes,
18k
